/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Wish = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addWish' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllWishes' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
  'getAllWishesByName' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
  'getWish' : IDL.Func([IDL.Text], [Wish], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Wish = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addWish' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllWishes' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
    'getAllWishesByName' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
    'getWish' : IDL.Func([IDL.Text], [Wish], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };